# Generated by Django 5.0.6 on 2024-05-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_app', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.ImageField(upload_to='post_images', verbose_name='Изображение'),
        ),
    ]
